/**
 * @ Author: Prajakta kulkarni
 * @ Create Time: 2022-09-13 10:37:43
 * @ Modified by: Your name
 * @ Modified time: 2022-09-13 10:40:36
 * @ Description:Create a form page considering Heading of page should be ‘Candidate Form’ below lightning-input fields

 */

import { createElement } from 'lwc';
import Day2lwcassignment from 'c/day2lwcassignment';

describe('c-day2-lwcassignment', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-day2-lwcassignment', {
            is: Day2lwcassignment
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});